### ISSUE TITLE
Automatically ask for PIN after reboot/shutdown

### ISSUE THREAD

**Issue by MiguelRipoll23** [Microsoft/companion-device-framework#1]
If makes sense to avoid the two clicks required to change your sign-in option, the "Sign in with other options" and clicking the icon corresponding to your other option.

**Comment by mu-triv** [comment]
Once I signed out, I can not sign in using my companion device. Windows 10 displays: "After a restart or logoff, the device requires verification before using it. Use another sign in option."

Is there any way to sign in using the companion device after signing out?

**Comment by HWataru** [comment]
@MiguelRipoll23 
I think this is not issue related Companion Device App.

@mu-triv 
>Is there any way to sign in using the companion device after signing out?

I think there is no way to sign in using the companion device.
Companion device only unlock your PC if Windows Hello is setup.

https://docs.microsoft.com/en-us/windows/uwp/security/companion-device-unlock
> Windows **Unlock** with Windows Hello companion (IoT) devices

**Comment by MiguelRipoll23** [comment]
@HWataru 

That's correct, this is Windows 10 related so I'll close this issue.
